### ISSUE TITLE
选择题点击结算按钮后,得分为0

### ISSUE THREAD

**Issue by ddayzzz** [ctuu/question-is-boundless#1]
RT
感谢大佬提供的平台。发现有些问题：
![TIM截图20190624123555](https://user-images.githubusercontent.com/22568844/59992181-0de99100-967d-11e9-9502-0f4b79db953e.png)

最终是点击`提交`按钮还是`结算`按钮呢？

**Comment by ctuu** [comment]
`提交` 是指提交当前题目的答案。

现在网页改了，`下一题`按钮在`提交`答案之前不会出现。

以前让它们同时出现就是为了方便我跳题调 BUG。

`提交`按钮现在改为`确认`，逻辑应该会比以前清晰。
